name: Run test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        working-directory: example
    steps:
    - uses: actions/checkout@v4
    - run: swift test
    # - run: npm ci
    #   working-directory: example/TSClient
    # - run: ./test.sh vapor
    # - run: ./test.sh hummingbird
