name: Run test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example
    steps:
    - uses: swift-actions/setup-swift@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@v3
    - run: npm ci
      working-directory: example/TSClient
    - run: ./test.sh
